name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: "Output of `agentsys --version` or `agnix --version`"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Claude Code
        - OpenCode
        - Codex CLI
        - Gemini CLI
        - Other
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: "e.g., macOS 15.2, Ubuntu 24.04, Windows 11"
    validations:
      required: true
